# Generated by Django 5.1.4 on 2025-06-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_crop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField(verbose_name='Nitrogen')),
                ('p', models.FloatField(verbose_name='Phosphorus')),
                ('k', models.FloatField(verbose_name='Potassium')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField(verbose_name='pH')),
                ('rainfall', models.FloatField()),
                ('label', models.CharField(max_length=70, verbose_name='Crop')),
            ],
            options={
                'verbose_name': 'Crop Dataset Entry',
                'verbose_name_plural': 'Crop Dataset Entries',
            },
        ),
        migrations.CreateModel(
            name='CropRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
