# Generated by Django 5.1.4 on 2025-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0005_contact_cropdataset_croprecommendationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCropData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(verbose_name='Nitrogen')),
                ('p', models.IntegerField(verbose_name='Phosphorus')),
                ('k', models.IntegerField(verbose_name='Potassium')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity in percentage')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('rainfall', models.FloatField(help_text='Rainfall in mm')),
                ('label', models.CharField(max_length=70, verbose_name='Crop')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Add Data to Dataset',
                'verbose_name_plural': 'Add Data to Dataset',
            },
        ),
    ]
